server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: localdev
  application:
    name: jwtauth
