spring.security:
  oauth2.client:
    registration.api:
      client-id: api
      client-secret: apipassword
      client-name: api
      scope: read
      authorization-grant-type: password
      redirect-uri-template:
      provider: jwtauth
    provider.jwtauth:
      token-uri: http://localhost:8080/oauth/token
      authorization-uri: http://localhost:8080/oauth/authorize
#      user-info-uri: http://localhost:8080/oauth/check_token

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: DEBUG
        web: DEBUG
      hibernate: DEBUG