server:
  port: 8888

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JKGrave/JwtAuthDemo-Repo.git